//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace isaac_tanti_sm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilePreference
    {
        public int preference_id { get; set; }
        public Nullable<bool> name { get; set; }
        public Nullable<bool> email { get; set; }
        public Nullable<bool> birthday { get; set; }
        public Nullable<bool> gender { get; set; }
    }
}
